var namespacestan =
[
    [ "internal", "d4/dc7/namespacestan_1_1internal.html", "d4/dc7/namespacestan_1_1internal" ],
    [ "math", "d4/d84/namespacestan_1_1math.html", "d4/d84/namespacestan_1_1math" ],
    [ "error_index", "d2/df5/structstan_1_1error__index.html", "d2/df5/structstan_1_1error__index" ],
    [ "eval_return_type", "dd/d1c/structstan_1_1eval__return__type.html", "dd/d1c/structstan_1_1eval__return__type" ],
    [ "is_autodiff", "d1/dff/structstan_1_1is__autodiff.html", null ],
    [ "is_constant", "d5/d70/structstan_1_1is__constant.html", null ],
    [ "is_constant< T, require_eigen_t< T > >", "d6/d39/structstan_1_1is__constant_3_01_t_00_01require__eigen__t_3_01_t_01_4_01_4.html", null ],
    [ "is_constant< T, require_std_vector_t< T > >", "da/d0f/structstan_1_1is__constant_3_01_t_00_01require__std__vector__t_3_01_t_01_4_01_4.html", null ],
    [ "is_detected", "da/d6f/structstan_1_1is__detected.html", null ],
    [ "is_detected< T, Op, void_t< Op< T > > >", "d0/d18/structstan_1_1is__detected_3_01_t_00_01_op_00_01void__t_3_01_op_3_01_t_01_4_01_4_01_4.html", null ],
    [ "is_double_or_int", "dd/d41/structstan_1_1is__double__or__int.html", null ],
    [ "is_eigen", "dc/d7d/structstan_1_1is__eigen.html", null ],
    [ "is_eigen_array", "dc/d22/structstan_1_1is__eigen__array.html", null ],
    [ "is_eigen_col_vector", "d6/d37/structstan_1_1is__eigen__col__vector.html", null ],
    [ "is_eigen_contiguous_map", "d7/d7c/structstan_1_1is__eigen__contiguous__map.html", null ],
    [ "is_eigen_matrix", "d8/d54/structstan_1_1is__eigen__matrix.html", null ],
    [ "is_eigen_row_vector", "dd/dc1/structstan_1_1is__eigen__row__vector.html", null ],
    [ "is_eigen_scalar_check", "d7/d47/structstan_1_1is__eigen__scalar__check.html", null ],
    [ "is_eigen_value_check", "dc/db2/structstan_1_1is__eigen__value__check.html", null ],
    [ "is_eigen_vector", "d7/d3b/structstan_1_1is__eigen__vector.html", null ],
    [ "is_eigen_vector_scalar_check", "d2/d12/structstan_1_1is__eigen__vector__scalar__check.html", null ],
    [ "is_eigen_vector_value_check", "d4/dca/structstan_1_1is__eigen__vector__value__check.html", null ],
    [ "is_fvar", "d4/df3/structstan_1_1is__fvar.html", null ],
    [ "is_matrix_cl", "da/d2a/structstan_1_1is__matrix__cl.html", null ],
    [ "is_matrix_cl_scalar_check", "d9/d11/structstan_1_1is__matrix__cl__scalar__check.html", null ],
    [ "is_matrix_cl_value_check", "d8/d06/structstan_1_1is__matrix__cl__value__check.html", null ],
    [ "is_stan_scalar", "da/d8f/structstan_1_1is__stan__scalar.html", null ],
    [ "is_std_vector", "d0/db6/structstan_1_1is__std__vector.html", null ],
    [ "is_std_vector_scalar_check", "df/d05/structstan_1_1is__std__vector__scalar__check.html", null ],
    [ "is_std_vector_value_check", "d2/d49/structstan_1_1is__std__vector__value__check.html", null ],
    [ "is_var", "df/d9d/structstan_1_1is__var.html", null ],
    [ "is_var_or_arithmetic_type", "dd/d4f/structstan_1_1is__var__or__arithmetic__type.html", null ],
    [ "is_vector", "d4/d82/structstan_1_1is__vector.html", null ],
    [ "is_vector_like", "d3/d45/structstan_1_1is__vector__like.html", null ],
    [ "is_vector_like_scalar_check", "d7/d30/structstan_1_1is__vector__like__scalar__check.html", null ],
    [ "is_vector_like_value_check", "df/d5f/structstan_1_1is__vector__like__value__check.html", null ],
    [ "is_vector_scalar_check", "d0/d4d/structstan_1_1is__vector__scalar__check.html", null ],
    [ "is_vector_value_check", "d2/d39/structstan_1_1is__vector__value__check.html", null ],
    [ "make_void", "d1/d2f/structstan_1_1make__void.html", "d1/d2f/structstan_1_1make__void" ],
    [ "partials_return_type", "d3/d04/structstan_1_1partials__return__type.html", "d3/d04/structstan_1_1partials__return__type" ],
    [ "partials_return_type< T >", "d0/d38/structstan_1_1partials__return__type_3_01_t_01_4.html", "d0/d38/structstan_1_1partials__return__type_3_01_t_01_4" ],
    [ "partials_type", "d0/db7/structstan_1_1partials__type.html", "d0/db7/structstan_1_1partials__type" ],
    [ "partials_type< T, require_fvar_t< T > >", "db/d98/structstan_1_1partials__type_3_01_t_00_01require__fvar__t_3_01_t_01_4_01_4.html", "db/d98/structstan_1_1partials__type_3_01_t_00_01require__fvar__t_3_01_t_01_4_01_4" ],
    [ "partials_type< T, require_var_t< T > >", "d4/da0/structstan_1_1partials__type_3_01_t_00_01require__var__t_3_01_t_01_4_01_4.html", "d4/da0/structstan_1_1partials__type_3_01_t_00_01require__var__t_3_01_t_01_4_01_4" ],
    [ "plain_type", "d9/dc8/structstan_1_1plain__type.html", "d9/dc8/structstan_1_1plain__type" ],
    [ "plain_type< T, require_eigen_t< T > >", "de/dee/structstan_1_1plain__type_3_01_t_00_01require__eigen__t_3_01_t_01_4_01_4.html", "de/dee/structstan_1_1plain__type_3_01_t_00_01require__eigen__t_3_01_t_01_4_01_4" ],
    [ "return_type", "d8/d68/structstan_1_1return__type.html", "d8/d68/structstan_1_1return__type" ],
    [ "return_type< T >", "d9/d8d/structstan_1_1return__type_3_01_t_01_4.html", "d9/d8d/structstan_1_1return__type_3_01_t_01_4" ],
    [ "scalar_seq_view", "d0/d32/classstan_1_1scalar__seq__view.html", null ],
    [ "scalar_type", "d6/dd9/structstan_1_1scalar__type.html", "d6/dd9/structstan_1_1scalar__type" ],
    [ "scalar_type< T, require_matrix_cl_t< T > >", "d3/df8/structstan_1_1scalar__type_3_01_t_00_01require__matrix__cl__t_3_01_t_01_4_01_4.html", "d3/df8/structstan_1_1scalar__type_3_01_t_00_01require__matrix__cl__t_3_01_t_01_4_01_4" ],
    [ "scalar_type_base", "db/d13/structstan_1_1scalar__type__base.html", "db/d13/structstan_1_1scalar__type__base" ],
    [ "scalar_type_pre", "d5/d53/structstan_1_1scalar__type__pre.html", "d5/d53/structstan_1_1scalar__type__pre" ],
    [ "StdVectorBuilder", "df/db9/classstan_1_1_std_vector_builder.html", "df/db9/classstan_1_1_std_vector_builder" ],
    [ "value_type", "dd/d27/structstan_1_1value__type.html", "dd/d27/structstan_1_1value__type" ],
    [ "value_type< T, require_matrix_cl_t< T > >", "d3/d95/structstan_1_1value__type_3_01_t_00_01require__matrix__cl__t_3_01_t_01_4_01_4.html", "d3/d95/structstan_1_1value__type_3_01_t_00_01require__matrix__cl__t_3_01_t_01_4_01_4" ],
    [ "vector_seq_view", "db/d03/classstan_1_1vector__seq__view.html", null ],
    [ "VectorBuilder", "da/d7e/classstan_1_1_vector_builder.html", "da/d7e/classstan_1_1_vector_builder" ],
    [ "VectorBuilderHelper", "d6/d66/classstan_1_1_vector_builder_helper.html", "d6/d66/classstan_1_1_vector_builder_helper" ],
    [ "VectorBuilderHelper< T1, true, false >", "d0/dc3/classstan_1_1_vector_builder_helper_3_01_t1_00_01true_00_01false_01_4.html", "d0/dc3/classstan_1_1_vector_builder_helper_3_01_t1_00_01true_00_01false_01_4" ],
    [ "VectorBuilderHelper< T1, true, true >", "d2/dfa/classstan_1_1_vector_builder_helper_3_01_t1_00_01true_00_01true_01_4.html", "d2/dfa/classstan_1_1_vector_builder_helper_3_01_t1_00_01true_00_01true_01_4" ]
];